### ISSUE TITLE
State Machine vs AbstractNState class

### ISSUE THREAD

**Issue by jordiandreu** [mxcube/HardwareRepository#453] opened 2019-12-10 15:05 UTC
Start a discussion about the implementation of the State Machine concept and the AbstractNState HardwareObject class.

**Comment by marcus-oscarsson** [comment] 2019-12-10 16:19
I'm closing this one since it seems like its a duplicate of #451, feel free to open it if you don't think its the case :)

**Closed by marcus-oscarsson** 2019-12-10 16:19 UTC
